### ISSUE TITLE
Issues with Item pipes

### ISSUE THREAD

**Issue by SL1200** [Vanhal/Zoooooom#2]
Hi there, I tried testing your mod but seem to have a problem. 
I have furnace top fed with item to cook and bottom fed with fuel and nothing is transferring on any of the item pipes. I've tried right-clicking with empty hand on the pipes but nothing happens.
I'm on 1.8.9 and tried running via both Eclipse and normal forge launcher.

**Comment by Vanhal** [comment]
Fuel in the side?

**Comment by SL1200** [comment]
Lol my bad was clicking wrong part of pipe I see it adds a export bus as it were, all sorted now :) And nice one pal been a long time waiting for a good pipe mod many thanks.
